export const initialValues = {
  name: "",
  angleFromNorth: 0,
  internalVolume: 0,
  height: 0,
  length: 0,
  width: 0,
  porosityFore: 0,
  porosityAft: 0,
  porosityPort: 0,
  porosityStarboard: 0,
  wallAreaFore: 0,
  wallAreaAft: 0,
  wallAreaPort: 0,
  wallAreaStarboard: 0,
  inclinationFore: 0,
  inclinationAft: 0,
  inclinationPort: 0,
  inclinationStarboard: 0,
  wavesFile: "",
  currentsFile: "",
};
